LOCAL nUME
local numero := 42
            
        
        // teste vou tentar limpar a tela
        clear screen
        
        INPUT "DIGITE UMA COISA QUALQUER : " to nUME

// teste de comentario no programa
        ? n
        

// teste funcao segundos
        ? seconds()

        // teste funcao que traz o sistema operacional
        ? os()

        // teste funcao que traz hora
        ? time()

// teste funcao que traz raiz quadrada
        ? sqrt(467)
